name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-uv/setup-uv@v5
        with:
          version: "0.8.17"
          enable-cache: true
      - name: Install python
        run: uv python install
      - name: Install dependencies
        run: uv sync --dev
      - name: Run tests
        run: uv run pytest tests

